PREDEFINED_LIST = {"24 hours non":"24 hours non - occupational accident coverage",
                   "24 hour non":"24 hours non - occupational accident coverage",
"30 days Notice":"30 days Notice of Cancellation on pro rata basis by either side.",
"Additions & Deletions" :"Additions & Deletions on automatic basis - with adjustment at policy expiry",
"Claim preparation clause":"Claim preparation clause",
 "Automatic extension":"Automatic extension of policy for one month, at pro rata additional premium.",

"Cover extended":"Cover extended for medical treatment following a covered claim outside Country of Work and reimbursed on actual incurred up to agreed Limit for Medical Expenses.",
"Cover for employees":"Cover for employees participating in social and sports activities conducted under the auspices of the insured, if any.",
"Cover for work related" :"Cover for work related accidents and bodily injuries during overtime, night shifts and work on public holidays & weekends (outside business hours) - 24 hours occupational cover.",
"Cross Liability":"Cover to be extended whilst the employee is being transported to and from work",
"Employee to Employee Extension":"Employee to Employee Extension",
"Errors & Omissions Clause":"Errors & Omissions Clause (all employees as per the wage roll records are covered).",
"Extension to cover":"Extension to cover for Sunstroke / Heat Stroke, Hernia and Industrial Diseases.",
"Funeral Expenses":"Funeral Expenses if repatriation is not possible/required - QAR 5,000 per person.",
"Including Employees ":"Including Employees on temporary hire or of subcontractors for whom the insured is responsible or not under the sponsorship of the Insured but working for them and listed in the Payroll",
"Including Insured":"Including Insured's Employees Whilst On Flights And/or Commuting From/To Country of Work provided they are not part of the flight as aircraft crew.",
"Indemnity to Principal":"Indemnity to Principal Clause.",
"newly hired employees":"Insured's newly hired employees whilst on incoming flights from their country of origin to Country of Employment.",
"Legal and Defense":"Legal and Defense costs to be in Addition to the Employer Liability",
"Medical Expenses Clause":"Medical Expenses Clause – up to a limit of QAR 15,000 per employee per accident at Private Hospitals / Private Clinics",
"Primary Insurance Clause":"Primary Insurance Clause (Non contributory)",
"Repatriation Expenses Clause":"Repatriation Expenses Clause - of mortal remains of a deceased employee or a seriously injured employee to his / her home country on medical advice up to QAR 15,000 per person (including costs of accompanying person).",
"Waiver of Subrogation":"Waiver of Subrogation Clause, as applicable."}


BENIFIT_LIST=["Insured",
"Coverage",
"No. of Employees",
"Jurisdiction",
"Period",
"Deductible",
'Premium',
"24 hours non - occupational accident coverage",
"30 days Notice of Cancellation on pro rata basis by either side.",
"Additions & Deletions on automatic basis - with adjustment at policy expiry",
"Automatic extension of policy for one month, at pro rata additional premium.",
"Claim preparation clause.",
"Cover extended for medical treatment following a covered claim outside Country of Work and reimbursed on actual incurred up to agreed Limit for Medical Expenses.",
"Cover for employees participating in social and sports activities conducted under the auspices of the insured, if any.",
"Cover for work related accidents and bodily injuries during overtime, night shifts and work on public holidays & weekends (outside business hours) - 24 hours occupational cover.",
"Cover to be extended whilst the employee is being transported to and from work",
"Cross Liability",
"Employee to Employee Extension",
"Errors & Omissions Clause (all employees as per the wage roll records are covered).",
"Extension to cover for Sunstroke / Heat Stroke, Hernia and Industrial Diseases.",
"Funeral Expenses if repatriation is not possible/required - QAR 5,000 per person.",
"Including Employees on temporary hire or of subcontractors for whom the insured is responsible or not under the sponsorship of the Insured but working for them and listed in the Payroll",
"Including Insured's Employees Whilst On Flights And/or Commuting From/To Country of Work provided they are not part of the flight as aircraft crew.",
"Indemnity to Principal Clause.",
"Insured's newly hired employees whilst on incoming flights from their country of origin to Country of Employment.",
"Legal and Defense costs to be in Addition to the Employer Liability",
"Medical Expenses Clause – up to a limit of QAR 15,000 per employee per accident at Private Hospitals / Private Clinics",
"Primary Insurance Clause (Non contributory)",
"Repatriation Expenses Clause - of mortal remains of a deceased employee or a seriously injured employee to his / her home country on medical advice up to QAR 15,000 per person (including costs of accompanying person).",
"Waiver of Subrogation Clause, as applicable.",
"Rate",
"Quotation",
"Estimated annual wages"]

